### PR TITLE
Rename files to PSR convention

### LINKED ISSUE #1: Class file names
Hello Josh!
Currently class files names and directory structure follows neither WPCS nor PSR-4.

Please consider going with PSR-4.

### PR DESCRIPTION
**Pull request by joshcanhelp**
Fixes #1 

https://www.php-fig.org/bylaws/psr-naming-conventions/

CC @szepeviktor

### CODE REVIEW

**Comment by szepeviktor** [comment]
PSR-4 structured classes can be loaded with Composer autoloader `"psr4": ...`
WPCS ones with https://github.com/szepeviktor/debian-server-tools/blob/master/webserver/wp-install/wordpress-autoloader.php#L3
Please see https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/#naming-conventions

What do you think?

**Comment by szepeviktor** [comment]
Issuing `composer2 dump-autoload -o`

```
Class WpUnitTestHelpers\Exceptions\RedirectHaltException located in ./src/exceptions/RedirectHaltException.php does not comply with psr-4 autoloading standard. Skipping.
Class WpUnitTestHelpers\Exceptions\AjaxHaltException located in ./src/exceptions/AjaxHaltException.php does not comply with psr-4 autoloading standard. Skipping.
Class WpUnitTestHelpers\Exceptions\HttpHaltException located in ./src/exceptions/HttpHaltException.php does not comply with psr-4 autoloading standard. Skipping.
Class WpUnitTestHelpers\Exceptions\WpDieHaltException located in ./src/exceptions/WpDieHaltException.php does not comply with psr-4 autoloading standard. Skipping.
Class WpUnitTestHelpers\Helpers\HookHelpersTrait located in ./src/helpers/HookHelpersTrait.php does not comply with psr-4 autoloading standard. Skipping.
Class WpUnitTestHelpers\Helpers\AjaxHelpersTrait located in ./src/helpers/AjaxHelpersTrait.php does not comply with psr-4 autoloading standard. Skipping.
Class WpUnitTestHelpers\Helpers\WpDieHelperTrait located in ./src/helpers/WpDieHelperTrait.php does not comply with psr-4 autoloading standard. Skipping.
Class WpUnitTestHelpers\Helpers\WpScriptsHelperTrait located in ./src/helpers/WpScriptsHelperTrait.php does not comply with psr-4 autoloading standard. Skipping.
Class WpUnitTestHelpers\Helpers\HttpHelpersTrait located in ./src/helpers/HttpHelpersTrait.php does not comply with psr-4 autoloading standard. Skipping.
Class WpUnitTestHelpers\Helpers\RedirectHelpersTrait located in ./src/helpers/RedirectHelpersTrait.php does not comply with psr-4 autoloading standard. Skipping.
```

**Comment by joshcanhelp** [comment]
@szepeviktor - I think we're good here. I installed this branch, made the naming adjustments, and it works as expected.

https://github.com/joshcanhelp/wp-test-plugin/compare/update-test-helper-lib

**Comment by szepeviktor** [comment]
There are still a lot of

```
Class WpUnitTestHelpers\Helpers\RedirectHelpersTrait located in ./src/helpers/RedirectHelpersTrait.php does not comply with psr-4 autoloading standard. Skipping.
```

The directory should called `Helpers`.
Test with `composer dump-autoload -o` in this repo.

**Comment by joshcanhelp** [comment]
I'm not seeing the same errors:

```bash
~/Sites/wp-unit-test-helpers fix-naming
❯ composer dump-autoload -o
Generating optimized autoload files

~/Sites/wp-unit-test-helpers fix-naming
```

**Comment by szepeviktor** [comment]
You may be using Composer v1.
Try downloading v2 as `~/bin/composer2`
https://getcomposer.org/download/2.0.8/composer.phar

**Comment by joshcanhelp** [comment]
Tried Composer 2 as well:

```bash
~/Sites/wp-unit-test-helpers fix-naming
❯ php ~/Downloads/composer.phar dump-autoload -o
Generating optimized autoload files
Generated optimized autoload files containing 767 classes

~/Sites/wp-unit-test-helpers fix-naming
❯ php ~/Downloads/composer.phar --version
Composer version 2.0.8 2020-12-03 17:20:38

~/Sites/wp-unit-test-helpers fix-naming
```

**Comment by joshcanhelp** [comment]
I had already renamed them locally but git did not pick up on the changes. I think we're good here!

Thank you!!!!

**Pull request merged**
